# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x43hatService.proto\x12\x0c\x63hat_service\"D\n\x07Message\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x17\n\x0fnameDestination\x18\x02 \x01(\t\x12\x12\n\nnameSender\x18\x03 \x01(\t\"\'\n\x0b\x44\x65stination\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\"$\n\x0c\x43onfirmation\x12\x14\n\x0c\x63onfirmation\x18\x01 \x01(\x08\x32\x96\x01\n\nChatServer\x12\x42\n\x0bSendMessage\x12\x15.chat_service.Message\x1a\x1a.chat_service.Confirmation\"\x00\x12\x44\n\x0cRelayMessage\x12\x19.chat_service.Destination\x1a\x15.chat_service.Message\"\x00\x30\x01\x42\x37\n\x1bio.grpc.examples.iotserviceB\x0fIoTServiceProtoP\x01\xa2\x02\x04TEMPb\x06proto3')



_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
_DESTINATION = DESCRIPTOR.message_types_by_name['Destination']
_CONFIRMATION = DESCRIPTOR.message_types_by_name['Confirmation']
Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'ChatService_pb2'
  # @@protoc_insertion_point(class_scope:chat_service.Message)
  })
_sym_db.RegisterMessage(Message)

Destination = _reflection.GeneratedProtocolMessageType('Destination', (_message.Message,), {
  'DESCRIPTOR' : _DESTINATION,
  '__module__' : 'ChatService_pb2'
  # @@protoc_insertion_point(class_scope:chat_service.Destination)
  })
_sym_db.RegisterMessage(Destination)

Confirmation = _reflection.GeneratedProtocolMessageType('Confirmation', (_message.Message,), {
  'DESCRIPTOR' : _CONFIRMATION,
  '__module__' : 'ChatService_pb2'
  # @@protoc_insertion_point(class_scope:chat_service.Confirmation)
  })
_sym_db.RegisterMessage(Confirmation)

_CHATSERVER = DESCRIPTOR.services_by_name['ChatServer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.iotserviceB\017IoTServiceProtoP\001\242\002\004TEMP'
  _MESSAGE._serialized_start=35
  _MESSAGE._serialized_end=103
  _DESTINATION._serialized_start=105
  _DESTINATION._serialized_end=144
  _CONFIRMATION._serialized_start=146
  _CONFIRMATION._serialized_end=182
  _CHATSERVER._serialized_start=185
  _CHATSERVER._serialized_end=335
# @@protoc_insertion_point(module_scope)
